"""
pipeline/prompts.py
System prompts, CoT reasoning templates, and token-optimized prompt builders.
Implements Chain-of-Thought (CoT) and ReAct reasoning frameworks.
"""

# ─── System Prompt ─────────────────────────────────────────────────────────────

SYSTEM_PROMPT = """You are VulnSentinel, an enterprise-grade cybersecurity intelligence AI.

ROLE: Analyze CVE vulnerability data and generate structured threat intelligence reports.
PERSONA: Precise, factual, security-expert. No speculation. No guessing.

STRICT RULES:
1. ONLY use information from the provided CVE context. Never invent CVE IDs, scores, or details.
2. If context is insufficient, say: "Insufficient data in knowledge base."
3. NEVER provide exploit code, attack instructions, or offensive guidance.
4. NEVER answer questions outside cybersecurity vulnerability analysis.
5. Always cite the CVE ID for every claim you make.
6. Output MUST follow the structured format specified in each request.

OUTPUT FORMAT:
- Use clear section headers
- CVSS scores must be numeric (e.g., 9.8, not "critical")
- Patch recommendations must be actionable and specific
- Flag unverified claims with [UNVERIFIED]"""


# ─── CoT Reasoning Template ────────────────────────────────────────────────────

def build_cot_prompt(query: str, cve_chunks: list[dict]) -> str:
    """
    Build a Chain-of-Thought (CoT) prompt for multi-step vulnerability analysis.
    Token-optimized: strips metadata noise, keeps only essential text.
    """
    # Build context block (token-efficient: no redundant metadata)
    context_parts = []
    for i, cve in enumerate(cve_chunks, 1):
        # Strip raw document, keep only key fields
        chunk = f"""[{i}] {cve['cve_id']} | CVSS:{cve.get('cvss_score', 'N/A')} | {cve.get('severity', 'N/A')}
{cve['document'][:400]}"""  # Hard cap at 400 chars per chunk for token efficiency
        context_parts.append(chunk)

    context = "\n\n".join(context_parts)

    prompt = f"""QUERY: {query}

RETRIEVED CVE CONTEXT:
{context}

REASONING CHAIN (Chain-of-Thought):

Step 1 — IDENTIFY: Which CVEs in the context are directly relevant to the query?
Step 2 — ASSESS: What is the severity and impact of each relevant CVE?
Step 3 — CORRELATE: Are multiple CVEs related (same product, attack chain)?
Step 4 — RECOMMEND: What are the specific patch/mitigation actions?
Step 5 — SUMMARIZE: Generate the final structured report.

Now execute the reasoning chain and produce the report in this exact format:

## VulnSentinel Threat Intelligence Report

**Query:** {query}

### Executive Summary
[2-3 sentences summarizing the threat landscape]

### Critical Vulnerabilities Found
| CVE ID | CVSS | Severity | Description |
|--------|------|----------|-------------|
[Fill table from context only]

### Affected Systems & Products
[List products from context]

### Patch & Mitigation Recommendations
[Numbered, actionable steps with CVE references]

### Risk Assessment
**Overall Risk Level:** [CRITICAL/HIGH/MEDIUM/LOW]
**Immediate Action Required:** [Yes/No and why]

### References
[CVE reference URLs from context]

---
*Report generated by VulnSentinel | Data source: NVD/NIST*"""

    return prompt


# ─── ReAct Prompt for Complex Queries ──────────────────────────────────────────

def build_react_prompt(query: str, cve_chunks: list[dict]) -> str:
    """
    ReAct (Reasoning + Acting) prompt for complex multi-step queries.
    Used when query involves multiple software components or attack chains.
    """
    context_parts = []
    for i, cve in enumerate(cve_chunks, 1):
        chunk = f"[{i}] {cve['cve_id']} | {cve.get('severity', 'N/A')} | {cve['document'][:300]}"
        context_parts.append(chunk)
    context = "\n".join(context_parts)

    prompt = f"""QUERY: {query}
CONTEXT: {context}

Use ReAct framework:
Thought 1: What is the user asking about?
Action 1: Identify relevant CVEs from context
Observation 1: [List relevant CVE IDs]

Thought 2: What is the severity and business impact?
Action 2: Assess CVSS scores and affected systems
Observation 2: [Severity analysis]

Thought 3: What should be done immediately?
Action 3: Generate prioritized recommendations
Observation 3: [Actions list]

Final Answer: [Structured report as specified in system prompt]"""

    return prompt


# ─── Guardrail Check Prompt ────────────────────────────────────────────────────

def build_hallucination_check_prompt(response: str, cve_chunks: list[dict]) -> str:
    """
    Output guardrail: checks if LLM response contains claims not in retrieved context.
    """
    context_ids = [c["cve_id"] for c in cve_chunks]
    context_summary = ", ".join(context_ids)

    return f"""You are a fact-checker for VulnSentinel.

RETRIEVED CVE IDs (ground truth): {context_summary}

LLM RESPONSE TO CHECK:
{response[:1500]}

Task: Check if the response mentions any CVE IDs NOT in the retrieved list above.
Respond ONLY with JSON:
{{"hallucinated_cves": ["CVE-XXXX-XXXX", ...], "is_safe": true/false, "reason": "..."}}"""
